import mongoose from 'mongoose';

const jobPostingSchema = mongoose.Schema({
  title: { type: String, required: true },
  department: { type: String, required: true },
  location: { type: String, default: 'Remote' },
  type: { type: String, default: 'Full-time' },
  description: { type: String }, // Generated by AI
  requirements: { type: String },
  status: { type: String, enum: ['Open', 'Closed', 'Draft'], default: 'Open' },
  applicants: [{
    name: String,
    email: String,
    resumeUrl: String,
    appliedAt: { type: Date, default: Date.now },
    status: { type: String, default: 'New' }
  }]
}, { timestamps: true });

const JobPosting = mongoose.model('JobPosting', jobPostingSchema);
export default JobPosting;
